### ISSUE TITLE
HiLine conda install broken

### ISSUE THREAD

**Issue by claumer** [wtsi-hpag/HiLine#2]
Hello HPAG team,

I was interested in using HiLine to generate some Hi-C contact distance plots. I created a fresh environment and installed with "conda install hiline" as directed. However, when I try to read the documentation, I get the following errors:

---

(hiline) cl16@farm5-head2:/lustre/scratch123/tol/teams/blaxter/users/cl16/PromethION_Q20EA_cDNAs$ HiLine --help
Traceback (most recent call last):
  File "/lustre/scratch123/tol/teams/blaxter/users/cl16/miniconda3/envs/hiline/bin/HiLine", line 33, in <module>
    sys.exit(load_entry_point('HiLine==0.2.4', 'console_scripts', 'HiLine')())
  File "/lustre/scratch123/tol/teams/blaxter/users/cl16/miniconda3/envs/hiline/bin/HiLine", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/lustre/scratch123/tol/teams/blaxter/users/cl16/miniconda3/envs/hiline/lib/python3.9/importlib/metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "/lustre/scratch123/tol/teams/blaxter/users/cl16/miniconda3/envs/hiline/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/lustre/scratch123/tol/teams/blaxter/users/cl16/miniconda3/envs/hiline/lib/python3.9/site-packages/HiLine/__init__.py", line 1, in <module>
    from HiLine.main import Pipeline
  File "/lustre/scratch123/tol/teams/blaxter/users/cl16/miniconda3/envs/hiline/lib/python3.9/site-packages/HiLine/main.py", line 4877, in <module>
    @cli.resultcallback()
AttributeError: 'Group' object has no attribute 'resultcallback'

---

The conda environment is up to date according to "conda update --all". 

Is this an installation bug? Let me know if I can provide any further details.

Regards,
Chris L

**Comment by charlottewright** [comment]
Hi HPAG team and Chris,

I just tried to install HiLine via conda (same commands as above) and have the same error.

Any help to get this installed and running would be amazing!

Best wishes,

Charlotte

**Comment by sujaikumar** [comment]
HI @claumer @charlottewright 

I just tried it with an older python and it worked (I've learnt -- the hard way -- to try older python versions in conda installs that don't work)

```
conda create -n hiline -c bioconda hiline python=3.8
```

**Comment by charlottewright** [comment]
Hi @claumer @sujaikumar,

I tried the command that Sujai suggested above but still got the original error which Chris posted. However, I got the installation to work when I made a conda environment using the yml file made by Sujai with the above command. I'm attaching it here in case useful for others as a quick fix. The differences between Sujai and I's setup is conda versioning and linux vs using a farm - exact cause for this weird behaviour to be determined though! (change .txt to .yml)
[hiline.txt](https://github.com/wtsi-hpag/HiLine/files/11759997/hiline.txt)

**Comment by sujaikumar** [comment]
We still don't know what worked in my original command `conda create -n hiline -c bioconda hiline python=3.8` because the same command didn't install correctly on my mac (i.e. `HiLine --help` gave the error that @claumer got above)

When I try the hiline file by @charlottewright above (rename to hiline.yaml and make conda env from it `conda env create -f hiline.yaml -n hiline` then it works fine on linux, but not on mac).

I don't *really* understand conda but my best guess is that the specific packages/versions in the yaml are names for linux packages, not mac ones

**Comment by amakunin** [comment]
Hi @sujaikumar @claumer @charlottewright . I've hit the same issue and according to [an issue in another repo](https://github.com/omegacen/conda-depgraph/issues/9), the problem is with `click` version. The command that worked for me is

```
mamba create -n hiline -c conda-forge -c bioconda hiline click=7
```
The python version in this particular example turned out to be `3.9`, but it still works
